name: Packge And Release

# 检测到 src 文件内 java 文件有变动时执行workflow
on:
  push:
    paths:
      - '**/*src/**/*.java'

jobs:
  package_publish:
    # 配置权限
    permissions: write-all
    # 指定运行的虚拟环境
    runs-on: ubuntu-latest
    steps:
    # 使用下载代码动作
    - name: Download Code
      uses: actions/checkout@v3
    # 安装 JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'z'
        cache: maven
    # Maven 打包 
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    # 将打包好的 jar 包 放到 staging 文件夹且重命名为 workflow-demo.jar
    - name: Move to other place
      run: mkdir staging && cp target/*.jar staging/workflow-demo.jar
    # 把项目的版本信息设置到环境变量中
    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        echo "done!"
    # 上传文件并发布 Release
    - name: Publish Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        # 引用在 Secrets 中设置环境变量
        repo_token: "${{ secrets.WF_TOKEN }}"
        automatic_release_tag: "${{ env.RELEASE_VERSION }}"
        prerelease: false
        title: "Release ${{ env.RELEASE_VERSION }}"
        files: |
          staging/workflow-demo.jar
